FROM python:3.9

WORKDIR /app 
#appp changed to app

COPY app.py /app
#appy changed to app

RUN pip install flask netifaces
#netiface changed to netiface 

EXPOSE 8000
# "eight thousand" changed to 8000

CMD ["python", "app.py"]
